# Generated by Django 5.0.6 on 2024-06-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogmodel_author_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
